config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_tasks
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
  get '/tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_Task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params_Task)
    @task.save!
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(params_Task)
    redirect_to task_path(@task)

  end

  def destroy
    @task.destroy

    redirect_to tasks_path
   end

  private

  def params_Task
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_Task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<br>
<br>
<%= form_for @task do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1> All Tasks </h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %> </li>
  <% end %>
</ul>
<%= link_to "Create Task", tasks_new_path  %>

app/views/tasks/new.html.erb
<br>
<br>
<%= form_for @task do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %> </h1>
<p><%= @task.details %> </p>
<p><%= @task.completed %> </p>

<%= link_to "Delete", task_path(@task), method: :delete, data: { confirm: "Are you sure ?"} %>
<%= link_to "update Task", edit_tasks_path  %>
<%= link_to "back", tasks_path  %>